# 项目相关配置
dlabeling:
  # 名称
  name: DLabeling
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
#  profile: ${UPLOAD_PATH}
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

  label:
    defaultDataRootDir: C:/Users/YYS/Desktop/temp

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/dlabeling
      username: root
      password: 12345678

      # 初始连接数
      initialSize: 10
      # 最小连接池数量
      minIdle: 20
      # 最大连接池数量
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      #连接出错后再尝试连接三次
      connection-error-retry-attempts: 3
      #超过时间限制是否回收
      remove-abandoned: true
      #超时时间；单位为秒。180秒=3分钟
      remove-abandoned-timeout: 20
      #关闭abanded连接时输出错误日志
      log-abandoned: false
      socketTimeout: 60000
      connectTimeout: 30000

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 12345678
    timeout: 30s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池的最大数据库连接数
        max-active: 300
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
      # 关闭超时时间
      shutdown-timeout: 1000

  messages:
    basename: message

# Token自定义配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 720

# MyBatis-Plus配置
mybatis:
  # 搜索指定包名
  typeAliasesPackage: com.dlabeling.**.domain
  # 配置mapperScan
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

captcha:
  enable: false

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10
server:
  port: 8080
